---
docker_registry: fujimiyashion
app_name: shining-english-api
app_port: 8080
app_replicas: 2
app_monitor_seconds: 30

# App env
app_mysql_host: "{{ hostvars['db-01']['ansible_host'] | default('localhost') }}"
app_mysql_port: 3306
app_mysql_database: shining_english
app_mysql_user: shining

# Nginx
nginx_backend_domain: staging-api.edgarden.net
nginx_ssl_email: admin@shiningenglish.vn
