---
- name: Setup App Server
  hosts: app_server
  vars_files:
    - ../inventory/group_vars/vault_db.yml
    - ../inventory/group_vars/vault_payos.yml
    - ../inventory/group_vars/vault_recaptcha.yml
    - ../inventory/group_vars/vault_swarm_token.yml
  roles:
    - common
    - docker
    - nginx
    - app
