CREATE TABLE lessons (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    slug VARCHAR(255) NOT NULL,
    course_id BIGINT UNSIGNED NOT NULL,
    lesson_group_id BIGINT UNSIGNED DEFAULT NULL,
    group_name VARCHAR(255) DEFAULT NULL,
    group_order INT DEFAULT 0,
    lesson_order INT DEFAULT 0,
    video_url VARCHAR(255) DEFAULT NULL,
    documents JSON DEFAULT NULL,
    document_names JSON DEFAULT NULL,
    description TEXT DEFAULT NULL,
    duration_minutes INT DEFAULT 0,
    star_reward_video INT DEFAULT 0,
    star_reward_quiz INT DEFAULT 0,
    has_quiz TINYINT(1) DEFAULT 0,
    is_preview_free TINYINT(1) DEFAULT 0,
    deleted_at TIMESTAMP NULL DEFAULT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_lessons_course (course_id),
    INDEX idx_lessons_group (lesson_group_id),
    FULLTEXT INDEX ft_lessons_name_slug (name, slug)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
